# @File: development.configs.yaml
# @Title: Kylon Application Configuration Settings (Development)
# @Description: Defines configuration parameters for the Kylon backend in development.
# @Author: thesyscoder (github.com/thesyscoder)

app:
    name: Kylon
    version: 1.0.0
    host: 0.0.0.0
    port: "8080"
    env: development
    readTimeout: 5s
    writeTimeout: 10s
    idleTimeout: 60s
    shutdownTimeout: 5s

logs:
    level: debug
    format: json # or text

storage:
    provider: minio
    bucket: kylon-dev-backups

kubernetes:
    kubeconfigPath: "" # Leave empty for in-cluster or default ~/.kube/config

ai:
    enabled: false
    modelEndpoint: "http://localhost:5000/predict"

scheduler:
    intervalMinutes: 60
